### ISSUE TITLE
.img files are not connected to release assets

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#122]
This changes when repo was migrated I believe. It would be super helpful to revert it to previous setup.

**Comment by sassanh** [comment]
@mehrdadfeller It is an issue only with our last action run, it happened because in the first run, building of the normal image failed and I had to manually re-run it, so the screenshots got built in the first attempt, while only the assets of the last run are shown.

You can choose other attempts using this select bar and you should be able to see screenshots assets:
<img width="313" alt="image" src="https://github.com/ubopod/ubo_app/assets/1270688/ac3018d5-423c-4b54-8a60-ef32f29abc3f">

Direct link of the attempt which has the screenshots: https://github.com/ubopod/ubo_app/actions/runs/9114239601/attempts/1
