### ISSUE TITLE
keyboard localisation stuck on UK layout

### ISSUE THREAD

**Issue by nubcore** [ubopod/ubo_app#131]
Used rPi Imager with v0.15.0 release tar.gz image. Used the "OS customisation option" and set hostname, user and WiFi successfully. The "Raspberry Pi Configuration" showed the keyboard as set correctly to US however Shift+2 != '@'. Locale was set to UK and changed to US but no help. Reset keyboard layout to generic 101 key, and key layout functioned as expected, changed back to generic 105 key and still worked. Unclear why customisation to apply US locale and when changed keyboard wasn't right until forcing it to change.

**Comment by mehrdadfeller** [comment]
@nubcore Thanks for the feedback. I believe this is related directly to Raspberry Pi OS behavior and not affected by Ubo app; I think I have seen a similar behavior though with one of my wireless keyboards. I guess if you use a wireless keyboard, the dongle may not communicate the exact keyboard type. When you connect a dongle to MacOS for example, a wizard shows up that asks a bunch of questions to determine the type of keyboard by asking the user to press some keys. 

Anyways, seems like the fix is to change the settings and apply to force the new settings. 

I am going to close this issue now but I will keep an eye on this and see if Raspberry Pi offers an improvement/fix.
